<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_admin_fa fa-sort-down</name>
   <tag></tag>
   <elementGuidId>2762531f-b8d2-447d-bd07-767b76e457f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-sort-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div[2]/header/div/div/div[3]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>db6b4462-e618-4cc8-81b1-acb0ade0881c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-sort-down</value>
      <webElementGuid>d3871226-2d5b-4693-9e78-7044cb15e299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrap-layout&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;wrap-main-content&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;wrap-header&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;user&quot;]/div[@class=&quot;relative&quot;]/i[@class=&quot;fa fa-sort-down&quot;]</value>
      <webElementGuid>9db8be5c-b0b5-4a3f-9c52-0703953abb62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div[2]/header/div/div/div[3]/div/i</value>
      <webElementGuid>0b10535a-74f2-4700-84c8-fa9cc967a658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>e8dbd94f-daf0-460d-b9fe-e318190b9010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
